# Generated by Django 5.0.2 on 2024-02-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='никнейм'),
        ),
    ]
