# Generated by Django 5.0.2 on 2024-02-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_first_name_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=25, unique=True, verbose_name='никнейм'),
        ),
    ]
